import './style.css'
import heroFarmImage from './assets/solar-cell-farm-power-station-alternative-energy-from-sun-scaled-e1774935900453.jpg'
import introImage from './assets/photovoltaics-solar-power-station-energy-from-natural.jpg'
import pvPotentialImage from './assets/pvpotential.png'
import landCoverImage from './assets/landcover.png'
import cropTypeImage from './assets/croptype.png'
import transmissionLinesImage from './assets/transline.png'
import soilMapsImage from './assets/soil maps of sk.png'
import landUseImage from './assets/land use.png'
import mrdemImage from './assets/mrdem.png'

const toAnchorId = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const arcgisEmbedScriptSrc = 'https://js.arcgis.com/5.0/embeddable-components/'

const navItems = [
  { label: 'Abstract', targetId: 'abstract' },
  { label: 'Introduction', targetId: 'introduction-heading' },
  {
    label: 'Datasets',
    targetId: 'datasets-heading',
    children: [
      { label: 'Photovoltaic Potential', targetId: toAnchorId('Photovoltaic Potential') },
      { label: 'Land Cover of Canada', targetId: toAnchorId('Land Cover of Canada') },
      { label: 'Annual Crop Inventory', targetId: toAnchorId('Annual Crop Inventory') },
      { label: 'Transmission Lines', targetId: toAnchorId('Transmission Lines') },
      { label: 'Thematic Soil Maps of Saskatchewan', targetId: toAnchorId('Thematic Soil Maps of Saskatchewan') },
      { label: 'Land Use', targetId: toAnchorId('Land Use') },
      { label: 'Medium Resolution Digital Elevation Model', targetId: toAnchorId('Medium Resolution Digital Elevation Model') },
    ],
  },
  {
    label: 'Methodology',
    targetId: 'methodology-heading',
    children: [
      { label: 'Research and Data Preparation', targetId: 'research-and-data-preparation' },
      { label: 'Data Preparation', targetId: 'data-preparation' },
      { label: 'Data Analysis - Standard MCE', targetId: 'data-analysis-standard-mce' },
      { label: 'Sensitivity Analysis', targetId: 'sensitivity-analysis-methodology' },
      { label: 'Data Analysis - Least Cost Pathway', targetId: 'data-analysis-least-cost-pathway' },
    ],
  },
  {
    label: 'Results',
    targetId: 'results-heading',
    children: [
      { label: 'Sensitivity Analysis - A comparison of models', targetId: 'sensitivity-analysis-results' },
      { label: 'Least-Cost Pathway', targetId: 'least-cost-pathway-results' },
      { label: 'Data Limitations', targetId: 'data-limitations-results' },
    ],
  },
  { label: 'Conclusion', targetId: 'conclusion-heading' },
  { label: 'Sources', targetId: 'sources-heading' },
]

const teamMembers = ['Raphael Caguiat', 'James Wang', 'Lucia Wu']

const datasets = [
  {
    title: 'Photovoltaic Potential',
    summary:
      'Information on the estimated amount of electricity that can be annually generated by photovoltaic systems for any location in Canada. Values are given in kWh/kWp.',
    source:
      'Data was obtained as a geodatabase file from Natural Resources Canada through the <a href="https://open.canada.ca/data/en/dataset/8b434ac7-aedb-4698-90df-ba77424a551f" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
    image: pvPotentialImage,
  },
  {
    title: 'Land Cover of Canada',
    summary:
      '30-meter land cover resolution map indicating physical cover of the Earth\'s Surface. Land cover types include Cropland, Mixed forests, wetlands, and the like.',
    source:
      'Data was obtained as a TIF file from the North American Land Change Monitoring System through the <a href="https://open.canada.ca/data/en/dataset/ee1580ab-a23d-4f86-a09b-79763677eb47" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
    image: landCoverImage,
  },
  {
    title: 'Annual Crop Inventory',
    summary:
      'Information on annual crop types of individual fields in Canada as documented by the Earth Observation Team of Agriculture and Agri-Food Canada (AAFC).',
    source:
      'Data was obtained as a TIF file from AAFC through the <a href="https://open.canada.ca/data/en/dataset/ba2645d5-4458-414d-b196-6303ac06c1c9" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
    image: cropTypeImage,
  },
  {
    title: 'Transmission Lines',
    summary:
      'A map showing the network of SaskPower Transmission Lines in Saskatoon.',
    source:
      'Data was obtained as an ArcGIS Pro layer file from <a href="https://www.arcgis.com/home/item.html?id=ec633b5f0b06465ab9bd7ec1af23948c" target="_blank" rel="noreferrer">ArcGIS Online</a>.',
    image: transmissionLinesImage,
  },
  {
    title: 'Thematic Soil Maps of Saskatchewan',
    summary:
      'A revised and condensed version of the CANSIS Saskatchewan Detailed Soils Database. For this project specifically, we are only interested in the soil slope column of the dataset.',
    source:
      'Data was obtained as an ArcGIS Pro polygon layer file from <a href="https://www.arcgis.com/home/item.html?id=c34b8c3f07234d10b6695802aec36ae7" target="_blank" rel="noreferrer">ArcGIS Online</a> and the <a href="https://open.canada.ca/data/en/dataset/ed36f4f3-2fb9-4241-8e29-6741e8b9e400" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
    image: soilMapsImage,
  },
  {
    title: 'Land Use',
    summary:
      'Information on the different land use classes across Canada. This includes settlement areas, roads, forests, wetlands, and croplands. The data was curated from several high-quality spatial datasets.',
    source:
      'Data was obtained as a TIF file from AAFC through the <a href="https://open.canada.ca/data/en/dataset/fa84a70f-03ad-4946-b0f8-a3b481dd5248" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
    image: landUseImage,
  },
  {
    title: 'Medium Resolution Digital Elevation Model',
    summary:
      'An integration of elevation data and DEM\'s derived from airborne lidar. This dataset was used to help calculate the least-cost pathway.',
    source:
      'Data was obtained as a GDAL virtual format (VRT) file from Natural Resources Canada through the <a href="https://open.canada.ca/data/en/dataset/18752265-bda3-498c-a4ba-9dfe68cb98da?res_page=1#resources" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
    image: mrdemImage,
  },
]

const landUseCostRows = [
  {
    code: '21',
    landuseClass: 'Settlement',
    definition:
      'Urban and rural residential, commercial, industrial, transportation or other built infrastructure use',
    weight: '100',
    explanation: 'Moderate cost to protect residential areas and malls, etc. from powerline construction',
  },
  {
    code: '22',
    landuseClass: 'High reflectance settlement',
    definition:
      'Settlement areas with high spectral reflectance such as pavement, buildings, or other surfaces with little to no observable vegetation',
    weight: '100',
    explanation: 'Moderate cost to protect residential areas and malls, etc. from powerline construction',
  },
  {
    code: '24',
    landuseClass: 'Settlement forest',
    definition: 'Settlement areas mostly or entirely covered by tree canopy',
    weight: '150',
    explanation: 'Moderately high cost to protect residential areas with more tree canopy',
  },
  {
    code: '25',
    landuseClass: 'Roads',
    definition: 'Primary, secondary and tertiary roads',
    weight: '10',
    explanation: 'Low cost to allow transmission lines to pass through open roads',
  },
  {
    code: '28',
    landuseClass: 'Vegetated settlement',
    definition:
      'Settlement areas with observable vegetation such as lawns, golf courses, and settlement areas with 30-50% tree canopy',
    weight: '175',
    explanation: 'Moderately high cost to protect residential areas with more tree canopy',
  },
  {
    code: '29',
    landuseClass: 'Very high reflectance settlement',
    definition:
      'Settlement areas with very high spectral reflectance such as pavement, buildings, or other surfaces with no observable vegetation',
    weight: '100',
    explanation: 'Moderate cost to protect residential areas and malls, etc. from powerline construction',
  },
  {
    code: '31',
    landuseClass: 'Water',
    definition: 'Open water',
    weight: '250',
    explanation:
      'High cost; virtually a barrier. People do not like powerlines affecting the visual character of lakes (taken from lab 4)',
  },
  {
    code: '41',
    landuseClass: 'Forest',
    definition:
      'Land covered by trees with a minimum canopy cover of 25% and a minimum height of 5m, or capable of growing to those measurements within 50 years',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '42',
    landuseClass: 'Forest wetland',
    definition:
      'Wetland with forest cover (canopy cover >40% and minimum height 5m, or capable of growing to those measurements within 50 years)',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '43',
    landuseClass: 'Forest regenerating after harvest (<20 years)',
    definition: 'Forest regenerating from tree harvesting activity that took place less than 20 years prior',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '44',
    landuseClass: 'Forest wetland regenerating after harvest (<20 years)',
    definition:
      'Wetland with forest cover regenerating from tree harvesting activity that took place less than 20 years prior',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '47',
    landuseClass: 'Forest regenerating after harvest (20-29 years)',
    definition:
      'Forest regenerating from tree harvesting activity that took place 20 to 29 years prior (this class is identified beginning in 2010)',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '48',
    landuseClass: 'Forest wetland regenerating after harvest (20-29 years)',
    definition:
      'Wetland with forest cover regenerating from tree harvesting activity that took place 20 to 29 years prior (this class is identified beginning in 2010)',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '49',
    landuseClass: 'Forest regenerating after fire (<20 years)',
    definition: 'Forest regenerating after a fire less than 20 years prior',
    weight: '250',
    explanation: 'High cost to protect forests and other areas of conservation',
  },
  {
    code: '51',
    landuseClass: 'Cropland',
    definition: 'Annual and perennial cropland',
    weight: '1',
    explanation: 'Base cost',
  },
  {
    code: '52',
    landuseClass: 'Annual cropland',
    definition: 'Annual cropland (identified beginning in 2015)',
    weight: '1',
    explanation: 'Base cost',
  },
  {
    code: '55',
    landuseClass: 'Land converted to cropland (<10 years)',
    definition:
      'Cropland that did not appear to be cropland 10 years prior (this class is identified beginning in 2010)',
    weight: '1',
    explanation: 'Base cost',
  },
  {
    code: '56',
    landuseClass: 'Land converted to annual cropland (<10 years)',
    definition:
      'Annual cropland that did not appear to be cropland 10 years prior (this class is identified beginning in 2015)',
    weight: '1',
    explanation: 'Base cost',
  },
  {
    code: '63',
    landuseClass: 'Prairie grassland',
    definition: 'Grassland and shrubland in the Prairie region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '64',
    landuseClass: 'Temperate grassland',
    definition: 'Grassland and shrubland in the Temperate region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '65',
    landuseClass: 'Temperate rainforest grassland',
    definition: 'Grassland and shrubland in a Temperate Rainforest region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '66',
    landuseClass: 'Boreal grassland',
    definition: 'Grassland and shrubland in the Boreal region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '67',
    landuseClass: 'Montane grassland',
    definition: 'Grassland and shrubland in a Montane region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '68',
    landuseClass: 'Alpine tundra grassland',
    definition: 'Grassland and shrubland in an Alpine Tundra region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '69',
    landuseClass: 'Arctic tundra grassland',
    definition: 'Grassland and shrubland in an Arctic Tundra region',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '73',
    landuseClass: 'Prairie wetland',
    definition: 'Wetland in the Prairie region, with vegetation at or above the surface of the water',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '74',
    landuseClass: 'Temperate wetland',
    definition: 'Wetland in the Temperate region, with vegetation at or above the surface of the water',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '75',
    landuseClass: 'Temperate rainforest wetland',
    definition:
      'Wetland in a Temperate Rainforest region, with vegetation at or above the surface of the water',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '76',
    landuseClass: 'Boreal wetland',
    definition: 'Wetland in the Boreal region, with vegetation at or above the surface of the water',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '78',
    landuseClass: 'Alpine tundra wetland',
    definition: 'Wetland in the Alpine Tundra region, with vegetation at or above the surface of the water',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '79',
    landuseClass: 'Arctic tundra wetland',
    definition: 'Wetland in the Arctic Tundra region, with vegetation at or above the surface of the water',
    weight: '250',
    explanation:
      'High cost for conservation reasons. Additionally, construction would be difficult in these areas',
  },
  {
    code: '81',
    landuseClass: 'Newly-detected settlement (<10 years)',
    definition:
      'Settlement (21) that was first identified as a Settlement land use less than 10 years prior (this class is identified beginning in 2010)',
    weight: '75',
    explanation: 'Moderate cost to protect residential areas and malls, etc. from powerline construction',
  },
  {
    code: '82',
    landuseClass: 'Newly-detected high reflectance settlement (<10 years)',
    definition:
      'High Reflectance Settlement (22) that was first identified as a Settlement land use less than 10 years prior (this class is identified beginning in 2010)',
    weight: '75',
    explanation: 'Moderate cost to protect residential areas and malls, etc. from powerline construction',
  },
  {
    code: '84',
    landuseClass: 'Newly-detected settlement forest (<10 years)',
    definition:
      'Settlement Forest (24) that was first identified as a Settlement land use less than 10 years prior (this class is identified beginning in 2010)',
    weight: '200',
    explanation: 'High cost to minimize construction in undeveloped areas and forests',
  },
  {
    code: '85',
    landuseClass: 'Newly-detected roads (<10 years)',
    definition: 'Primary, secondary and tertiary roads',
    weight: '10',
    explanation: 'Low cost to allow transmission lines to pass through open roads',
  },
  {
    code: '88',
    landuseClass: 'Newly-detected vegetated settlement (<10 years)',
    definition:
      'Vegetated Settlement (28) that was first identified as a Settlement land use less than 10 years prior (this class is identified beginning in 2010)',
    weight: '150',
    explanation: 'Moderately high cost to protect residential areas with more tree canopy',
  },
  {
    code: '89',
    landuseClass: 'Newly-detected very high reflectance settlement (<10 years)',
    definition:
      'Very High Reflectance Settlement (29) that was first identified as a Settlement land use less than 10 years prior (this class is identified beginning in 2010)',
    weight: '100',
    explanation: 'Moderate cost to protect residential areas and malls, etc. from powerline construction',
  },
  {
    code: '91',
    landuseClass: 'Other land',
    definition: 'Rock, beaches, ice, barren land',
    weight: '200',
    explanation: 'High cost as construction is impractical in these areas',
  },
  {
    code: '92',
    landuseClass: 'Snow and ice',
    definition: 'Snow and Ice on mountains (this class is identified only in 2020)',
    weight: '200',
    explanation: 'High cost as construction is impractical in these areas',
  },
]

const sources = [
  'Barth, B. (2016, July 15). So Shady: 10 Crops That Can Be Grown Without a Lot of Sun - Modern Farmer. Modern Farmer. https://modernfarmer.com/2016/07/shade-plants/',
  'Chasmanthium latifolium (Indian Wood Oats, Northern Sea Oats, River Oats, Wild Oats, Wood-oat) | North Carolina Extension Gardener Plant Toolbox. (n.d.). Plants.ces.ncsu.edu. https://plants.ces.ncsu.edu/plants/chasmanthium-latifolium/',
  'Cowbrough, M. (2025, September 5). Cereal rye as a cover crop in Ontario for field crop production – Field Crop News. Fieldcropnews.com. https://fieldcropnews.com/2025/09/cereal-rye-as-a-cover-crop-in-ontario-for-field-crop-production/',
  'Dal Prà, A., Miglietta, F., Genesio, L., Lanini, G. M., Bozzi, R., Morè, N., ... & Fabbri, M. C. (2024). Determination of feed yield and quality parameters of whole crop durum wheat (Triticum durum Desf.) biomass under agrivoltaic system. Agroforestry Systems, 98(8), 2861-2873.',
  'Douglas, R. (2024, March 18). Growing Barley: A Concise Guide for Small Farms. Small Farm Canada. https://www.smallfarmcanada.ca/gardens-crops/growing-barley-a-concise-guide-for-small-farms/',
  'Elmy, K. (2026a). Common Vetch (Vicia villosa) | Cover Crops Canada. Covercrops.ca. https://covercrops.ca/common-vetch/',
  'Elmy, K. (2026b). Proso Millet (Panicum milaceum) | Cover Crops Canada. Covercrops.ca. https://covercrops.ca/proso-millet/',
  'ginsengadmin. (2021, November 10). Canadian Ginseng: A Unique Growing Process - Ontario Ginseng Growers Association. Ontario Ginseng Growers Association. https://ginsengontario.com/panax-quinquefolius-ginseng-a-unique-growing-process/',
  'Government of Canada, S. C. (2022, June 15). Saskatchewan continues to live up to the title of breadbasket of Canada. https://www150.statcan.gc.ca/n1/pub/96-325-x/2021001/article/00008-eng.htm',
  'Hauger, S., Lieb, V., & Glaser, R. (2025). Spatial potential analysis and site selection for agrivoltaics in Germany. Renewable and Sustainable Energy Reviews, 213, 115469.',
  'Jamil, U., Bonnington, A., & Pearce, J. M. (2023). The agrivoltaic potential of Canada. Sustainability, 15(4), 3228.',
  'Pena-Calzada, K., Toledo, C., Garciga, J. P., Barrera-Cardoso, E. L., Iriondo-Pérez, M. E., Sotolongo-Hernández, E., & Scognamiglio, A. (2025). Advances and challenges of agrivoltaic in the Americas: a look at its current situation. Agroforestry Systems, 99(1), 8.',
  'The Paris Agreement | UNFCCC. (2016). Retrieved March 22, 2026. https://unfccc.int/process-and-meetings/the-paris-agreement.',
  'Trommsdorff, M., Kang, J., Reise, C., Schindele, S., Bopp, G., Ehmann, A., ... & Obergfell, T. (2021). Combining food and energy production: Design of an agrivoltaic system applied in arable and vegetable farming in Germany. Renewable and Sustainable Energy Reviews, 140, 110694.',
  'Ward, N., & Lewry, M. (2019). Saskatchewan | History, Population, Map, & Flag. In Encyclopædia Britannica. https://www.britannica.com/place/Saskatchewan',
  'Widmer, J., Christ, B., Grenz, J., & Norgrove, L. (2024). Agrivoltaics, a promising new tool for electricity and food production: A systematic review. Renewable and Sustainable Energy Reviews, 192, 114277.',
  'Images by Freepik. https://www.freepik.com/',
]

const app = document.querySelector<HTMLDivElement>('#app')

if (!document.querySelector(`script[src="${arcgisEmbedScriptSrc}"]`)) {
  const arcgisScript = document.createElement('script')
  arcgisScript.type = 'module'
  arcgisScript.src = arcgisEmbedScriptSrc
  document.head.appendChild(arcgisScript)
}

if (app) {
  app.innerHTML = `
    <div class="site-shell">
      <aside class="toc" aria-label="Table of contents">
        <button class="toc-button" type="button" aria-expanded="false" aria-controls="toc-panel">
          <span class="toc-button-lines" aria-hidden="true"><span></span><span></span><span></span></span>
          <span class="sr-only">Toggle table of contents</span>
        </button>

        <div class="toc-panel" id="toc-panel">
          <p class="toc-title">Table Of Contents</p>
          <nav class="toc-links">
            ${navItems
              .map(
                (item) =>
                  item.children?.length
                    ? `
                      <div class="toc-main-item">
                        <details class="toc-group">
                          <summary class="toc-group-summary">${item.label}</summary>
                          <div class="toc-sub-links">
                            <button type="button" class="toc-link" data-target="${item.targetId}">${item.label} Overview</button>
                            ${item.children
                              .map(
                                (child) =>
                                  `<button type="button" class="toc-link toc-sublink" data-target="${child.targetId}">${child.label}</button>`,
                              )
                              .join('')}
                          </div>
                        </details>
                      </div>
                    `
                    : `<div class="toc-main-item"><button type="button" class="toc-link toc-main-link" data-target="${item.targetId}">${item.label}</button></div>`,
              )
              .join('')}
          </nav>
        </div>

        <button class="toc-backdrop" type="button" aria-hidden="true" tabindex="-1"></button>
      </aside>

      <main class="page" id="top">
        <section class="hero section-card">
          <div class="hero-scene" aria-hidden="true" style="background-image: url('${heroFarmImage}')">
            <div class="hero-caption-wrap">
              <h1>Mapping Viable Areas for Agrivolatics in Saskatchewan</h1>
            </div>
          </div>
        </section>

        <section class="section-card team-section">
          <div class="section-heading">
            <h2>The Team</h2>
          </div>
          <div class="team-grid">
            ${teamMembers.map((member) => `<article class="team-card">${member}</article>`).join('')}
          </div>
        </section>

        <section class="section-card" id="abstract">
          <div class="section-heading">
            <h2>Abstract</h2>
          </div>
          <div class="prose">
            <p>
              Agrivoltaics is the co-development of land for both solar energy and agriculture. It is a currently developing area of research that may be a potent and sustainable solution to rising food and energy demand. Out of all provinces in Canada, Saskatchewan has the largest share of farmland; thus, there is high potential for agrivoltaics deployment in this province. In this project, we utilize Multi-Criteria Evaluation to analyze which areas in Saskatchewan are most suitable for agrivoltaics deployment. Furthermore, we developed a least-cost pathway to model a route from one of the potential agrivoltaics farms to a nearby power station.
            </p>
          </div>
        </section>

        <section class="section-card section-divider-top" id="introduction">
          <div class="section-heading">
            <h2 id="introduction-heading">Introduction</h2>
          </div>

          <div class="intro-flow">
            <figure class="content-figure intro-figure">
              <img class="figure-image figure-map" src="${introImage}" alt="Solar power station" />
            </figure>

            <div class="prose intro-prose">
              <p>
                Globally, countries must deal with the combined effects of population growth and climate change, which make it difficult to expand renewable energy sources while meeting increasing food demand. As the world works to limit global warming to +1.5°C above industrial levels as described in the Paris Agreement (UNFCCC, 2016), addressing this challenge only becomes more pressing. Solar photovoltaic (PV) energy is a key part to addressing this problem; however, it comes with the caveat of requiring significant land area. This need for land leads to conflicts with the agricultural sector (Widmer et al., 2024). As a result, agrivoltaics, which is essentially the co-development of land for both PV and agriculture, has emerged as a solution to this issue (Jamil et al., 2023; Pena-Calzada et al., 2024; Widmer et al., 2024).
              </p>
              <p>
                Saskatchewan, which is known as the breadbasket of Canada, accounted for 39.2% of Canada’s total farm area as of 2021 — that is the largest share among all Canadian provinces (Government of Canada, 2022). Additionally, about two-thirds of this total farm area, which equates to approximately 40 million acres, consists of cropland. Thus, it is theorized that even using a tiny portion of this land for agrivoltaics would allow the province to offset fuel-based electricity generation and would contribute greatly to the country’s energy needs.
                </p>
              <p>
                Overall, the goal of this study is to identify which areas in Saskatchewan offer the strongest suitability for agrivoltaics deployment through a Multi-Criteria Evaluation.
            </p>
            </div>
          </div>
        </section>

        <section class="section-card section-divider-top" id="datasets">
          <div class="section-heading">
            <h2 id="datasets-heading">Datasets</h2>
          </div>

          <div class="prose dataset-intro">
            <p>
              The majority of our data was obtained for free from the Government of Canada Open Government Portal.
              The sole exception to this is the transmission line data, which was obtained from ArcGIS Online.
            </p>
            <p>
              We obtained the most up-to-date versions of our data possible. However, it should be noted that this
              can mean different datasets are from different years (i.e. land cover data was last updated in 2020,
              crop type data was last updated in 2024).
            </p>
          </div>

          <div class="dataset-list">
            ${datasets
              .map(
                (dataset) => `
                  <article class="dataset-row${dataset.title === 'Transmission Lines' ? ' dataset-row-focus' : ''}">
                    <div class="dataset-copy">
                      <h3 id="${toAnchorId(dataset.title)}">${dataset.title}</h3>
                      <div class="figure-placeholder dataset-image">
                        <img class="figure-image" src="${dataset.image}" alt="${dataset.title}" />
                      </div>
                    </div>
                    <div class="dataset-text${dataset.title === 'Transmission Lines' ? ' dataset-text-fit' : ''}">
                      <p class="dataset-summary">${dataset.summary}</p>
                      <p class="dataset-source">${dataset.source}</p>
                    </div>
                  </article>
                `,
              )
              .join('')}
          </div>
        </section>

        <section class="section-card" id="methodology">
          <div class="section-heading">
            <h2 id="methodology-heading">Methodology</h2>
          </div>
          <div class="methodology-content">
            <p class="methodology-intro">There are five main phases of our analysis:</p>
            <ol class="methodology-phases">
              <li>Research and Data Preparation</li>
              <li>Data Analysis - Standard MCE</li>
              <li>Sensitivity Analysis</li>
              <li>Data Analysis - Least Cost Pathway</li>
            </ol>

            <h3 id="research-and-data-preparation">Research and Data Preparation</h3>

            <h4>Background research</h4>
            <p>
              First and foremost, a comprehensive literature review was conducted to understand what factors experts
              consider when assessing potential areas for agrivoltaics (AV) implementation. The factors and
              constraints that were selected for this project are listed in the Data Analysis - Standard MCE section
              of the methodology.
            </p>
            <p>
              Previous literature was also used as a reference for weighing these factors. Furthermore, information
              about the various datasets used for this analysis and how they were obtained is detailed in the <a href="#sources-heading">data sources page</a>.
            </p>

            <h4 id="data-preparation">Data Preparation</h4>
            <p>
              Many of the collected datasets covered the entire extent of Canada. Thus, it was necessary to clip and
              extract the data by mask to narrow the data layers to only Saskatchewan.
            </p>
            <p>
              Land cover and annual crop inventory data were gathered as TIF files. To use this data, we used the
              Build Attribute Table tool to access the non-spatial information in the datasets. Then, we used the
              Extract by Attribute table to isolate the values relevant to the project. Namely, we selected only
              cropland from the land cover data and shade-tolerant crops from the annual crop inventory. Crops were
              determined to be shade-tolerant if they were able to grow in partial shade, benefited from some shade
              as protection from too much heat, or were shown to have increased productivity under an agrivoltaic
              system in previous literature (Barth, 2016; Chasmanthium Latifolium (Indian Wood Oats, Northern Sea
              Oats, River Oats, Wild Oats, Wood-Oat) | North Carolina Extension Gardener Plant Toolbox, n.d.;
              Cowbrough, 2025; Dal Pra et al., 2024; Douglas, 2024; Elmy, 2026a; Elmy, 2026b; ginsengadmin, 2021;
              Trommsdorff et al., 2021).
            </p>
            <p>
              The photovoltaic potential map displays the estimated amount of electricity a solar photovoltaic system
              can generate at any location in Canada. The map consisted of overlapping polygons based on different
              specifications of a photovoltaic system (i.e., orientation, tilt) and time of year in months. To
              simplify the analysis, we used the Select by Attribute tool to isolate the polygons for photovoltaic
              systems with a south-facing orientation and latitude tilt. Furthermore, we used values measured over an
              annual period to account for year-round variation in solar radiation. Furthermore, the photovoltaic
              potential variable in the dataset was given as a range of values listed in a string (i.e., 1300-1400
              kWp/kWh); these were converted into numerical values for our analysis. Specifically, we defined the
              photovoltaic potential for each location as the upper bound of each range. As there were only 7 large
              polygons to add numeric values to, the values were added onto a copy of the feature by hand.
            </p>
            <p>
              We also made use of the thematic soil maps of Saskatchewan dataset, but only one variable in particular
              - soil slope. Like the photovoltaic potential data, the slope data was given in a range of values.
              However, there were over 67,0000 values present in the data. Thus, we used a Python script to take the
              upper range of the slope value and assign that value as the slope for each location.
            </p>
            <p>
              The Distance Accumulation tool was used on the SaskPower Transmission Lines dataset, which shows where
              power lines are located. This generated a new feature layer showing the distance away from the
              transmission lines at any location. Furthermore, the layer was limited to just the province of
              Saskatchewan.
            </p>

            <h3 id="data-analysis-standard-mce">Data Analysis - Standard MCE</h3>
            <p>We performed the standard Multi-Criteria Evaluation methodology for this project.</p>
            <p>The factors used for our MCE are as follows:</p>
            <ul class="methodology-factors">
              <li>
                <strong>Photovoltaic Potential:</strong> Photovoltaic potential refers to how much electricity would
                be generated by a solar photovoltaic system in a particular area.
              </li>
              <li>
                <strong>Soil slope:</strong> The steepness of the landscape surface, defined as the vertical change in
                elevation over a horizontal distance and expressed in percentage values. Having a slope of less than
                5% is ideal to reduce construction costs.
              </li>
              <li><strong>Distance from transmission line</strong></li>
            </ul>
            <p>
              Furthermore, there were three constraints used in our evaluation. First, we restricted the data to only
              crop land in Saskatchewan - our analysis focuses on which sections of the current crop land area are
              viable for AV, not discovering new areas to implement both crops and AV. Second, we further limited the
              crop land to the farms where shade-tolerant crops are being grown. It is important to note that AV is a
              currently developing area of research - as such, there is not yet an agreed upon method to deal with
              the problem of the solar PV arrays shading the crops. Moreover, it is unknown whether the increased
              energy production is worth the decrease in crop productivity (Pena-Calzada et al., 2025). Hence, we
              account for this by focusing only on shade-tolerant crops that may benefit from AV implementation.
              Lastly, we did not consider areas where the slope was greater than 25%. Experts assessed that having a
              slope that steep would make it so that construction costs would be too high past a certain point (Hauger
              et al., 2025). In that sense, soil slope was both a restraint and a factor in this project.
            </p>
            <p>
              Lastly, we then used a weighted sum to identify potential sites for AV implementation. Weighting and
              relative importance of factors were determined through an analytical hierarchical process and based on a
              similar study performed in Germany (Hauger et al., 2025). The aforementioned study had a wide variety of
              professionals - including researchers, farmers, agronomists, and power producers - conduct the pairwise
              comparisons. We referenced the comparison matrix displayed in Table 2 of the study, but only
              incorporated the criteria relevant to our study. These factors were then normalized to a consistent
              scale. This was done through the MSSmall and MSLarge functions. The following weights were then
              calculated for each factor:
            </p>
            <details class="methodology-table-toggle">
              <summary>Table 1: Factors selected as suitability criteria for the Multi-Criteria Evaluation and their assigned weights.</summary>
              <div class="methodology-table-wrap">
                <table class="methodology-table">
                  <thead>
                    <tr>
                      <th>Suitability criteria</th>
                      <th>Weight</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Photovoltaic potential</td>
                      <td>6.29%</td>
                    </tr>
                    <tr>
                      <td>Slope</td>
                      <td>26.54%</td>
                    </tr>
                    <tr>
                      <td>Distance from Transmission Line</td>
                      <td>67.16%</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </details>

            <h3 id="sensitivity-analysis-methodology">Sensitivity Analysis</h3>
            <p>
              The final step to complete the MCE analysis was to perform a sensitivity analysis. In short, we created
              a separate model where the weights of the factors were set to be equal. This was done to visualize how
              having different weights would affect the results.
            </p>
            <p>
              The results of each model were overlaid on each other. The produced map can be found on the <a href="#results-heading">results page</a>.
            </p>

            <h3 id="data-analysis-least-cost-pathway">Data Analysis - Least Cost Pathway</h3>
            <p>
              We also wanted to map the least cost pathway from one of the viable areas we identified to a nearby
              transmission line. We decided to focus on this area selected by our weighted model, as it seemed to be
              somewhat further from transmission lines and other power infrastructure in comparison to other areas.
            </p>
            <p>
              A full DEM was needed to calculate and generate the cost accumulation surface. Thus, we used a dataset
              with a much coarser resolution of 30m rather than the soil maps dataset, which had a higher
              resolution.
            </p>
            <p>
              Then, we assigned costs to the different terrain types included in our land use dataset (Table 2).
              These costs were joined with our land use raster, and then the raster was reclassified so that each
              pixel had an assigned land cost. We then used the Cost Accumulation and Single Path tools to create the
              least cost pathway.
            </p>

            <details class="methodology-table-toggle">
              <summary>Table 2: Land use types and their relative costs. A rationale for each assigned weight is included.</summary>
              <div class="methodology-table-wrap">
                <table class="methodology-table">
                  <thead>
                    <tr>
                      <th>Code</th>
                      <th>Landuse Class</th>
                      <th>Definition</th>
                      <th>Weights</th>
                      <th>Explanation</th>
                    </tr>
                  </thead>
                  <tbody>
                    ${landUseCostRows
                      .map(
                        (row) => `
                          <tr>
                            <td>${row.code}</td>
                            <td>${row.landuseClass}</td>
                            <td>${row.definition}</td>
                            <td>${row.weight}</td>
                            <td>${row.explanation}</td>
                          </tr>
                        `,
                      )
                      .join('')}
                  </tbody>
                </table>
              </div>
            </details>
          </div>
        </section>

        <section class="section-card" id="results">
          <div class="section-heading">
            <h2 id="results-heading">Results</h2>
          </div>
          <div class="prose results-prose">
            <p>
              Previous research indicates that Canada’s electrical energy needs can be provided solely by agrivoltaics
              even if we were to use only 1% of Canada’s land (Jamil et al., 2023). Saskatchewan, our area of focus,
              has a total area of about 650,000 square kilometers (Ward and Lewry, 2019). Accordingly, our models
              selected the best 1% of Saskatchewan’s land that would be most suitable for agrivoltaics deployment.
              More specifically, each model selected a total area of 6500 square kilometers, split into 10 areas each.
            </p>
            <p>
              The following map showcases the 10 most suitable locations as selected by each MCE model. The yellow
              sections indicate the areas selected by the weighted model. Likewise, the blue sections indicate areas
              selected by the equal model. Lastly, the red sections are areas that both of the models selected.
              Generally, the model selected areas towards the southern part of the province.
            </p>
          </div>
            <div class="results-map-placeholder">
              <arcgis-embedded-map
                style="height:600px;width:700px;max-width:100%;"
                item-id="b0ec6735f2fb44de9ddb04ea8b2da67c"
                theme="light"
                time-zone-label-enabled
                center="-104.74258956061414,53.05958518219305"
                scale="9244648.868618"
                portal-url="https://ubc.maps.arcgis.com"
              ></arcgis-embedded-map>
            </div>

            <div class="prose results-prose">
              <h3 id="sensitivity-analysis-results">Sensitivity Analysis - A comparison of models</h3>
              <p>
                Though there is some overlap, changing the weights significantly changed the selected areas. The
                overlapping areas, however, are both already quite near transmission lines. This is highly likely due
                to the assigned weighting for our model. To recap, we assigned weights of 67.16% to proximity to
                transmission lines, 26.54% to slope, and 6.29% to photovoltaic potential for the weighted model. In
                simpler terms, the weighted model highly values having agrivoltaic farms near existing power
                infrastructure.
              </p>
              <p>
                This highlights that the selection of suitable areas for agrivoltaics highly depends on what the
                interested parties value. As mentioned in the methodology section, our weighting and selected factors
                are essentially based on the insights of experts from Germany. It can be inferred that these experts
                valued the practicality of construction and implementation over sustainability or climate impacts -
                higher weights were assigned to variables like proximity to grid connection points, slope, and the
                German building code, while the lowest weights of 4% each were assigned to solar irradiation and climate
                water balance (Hauger et al., 2025). Thus, there is a strong possibility that if Canada-based experts or
                other types of professionals were consulted for this project, the weighting of variables and the
                subsequently selected areas may be completely different.
              </p>

              <h3 id="least-cost-pathway-results">Least-Cost Pathway</h3>
              <p>
                The calculated path is overall relatively straight. The area surrounding the farm consists mostly of
                cropland and roads, which we assigned the lowest weights to. Thus, the path was able to go straight
                through for the most part. Upon closer inspection, however, we see that the path avoids the areas we
                wanted it to. The path snakes through and avoids grasslands, shrublands, bodies of water, and settlements
                with high vegetation.
              </p>

              <h3 id="data-limitations-results">Data Limitations</h3>
              <p>
                We made use of the most up-to-date versions of each dataset we gathered. However, it should be noted
                that this means that some datasets are from different years. The photovoltaic potential map and land
                cover datasets, for example, were last updated in 2020, while the annual crop inventory was updated more
                recently in 2024.
              </p>
              <p>
                There are also a few coverage concerns with our data. The Thematic Soil Maps of Saskatchewan dataset did
                not cover all of the cropland that we originally planned to include in our analysis. To account for
                this, we further limited coverage to only include areas for which we had complete data.
              </p>
              <p>
                Lastly, the land use dataset we used for the least-cost pathway calculation did not include much detail
                when it came to settlements and residential areas. There was more focus placed on nature and types of
                land cover (i.e., cropland, forests, wetlands). Urban and rural residential, commercial, and industrial
                infrastructure were all grouped into one variable. Thus, we were unable to fully account for the
                variation in settlement and infrastructure types.
              </p>
            </div>
        </section>

        <section class="section-card conclusion-section" id="conclusion">
          <div class="section-heading">
            <h2 id="conclusion-heading">Conclusion</h2>
          </div>
          <div class="prose conclusion-prose">
            <p>
              This project mapped out the most suitable areas for agrivoltaics deployment in Saskatchewan, Canada.
              The factors that were considered in this analysis were soil slope, proximity to transmission lines, and
              photovoltaic potential. We also limited the analysis to only cover existing crop land, areas where
              shade-tolerant crops were being grown, and where the slope was not too steep. Furthermore, we mapped a
              least-cost pathway from one of the identified agrivoltaic farms to a nearby substation.
            </p>
            <p>
              Though the MCE analysis provides a limited view of opinions, it does provide a good starting point to
              understand what areas should be investigated. Future studies can incorporate the inputs of a wider
              variety of local experts to create a more robust model. Another group that would be important to
              include in a Canadian context, for example, is Indigenous communities. This could mean that future
              models may consider including more suitability criteria and likely have different weights assigned to
              each factor. Lastly, future research could build on this analysis by looking into finding new areas to
              start farms and implement agrivoltaics rather than simply focusing on current agricultural areas.
            </p>
          </div>
        </section>

        <section class="section-card sources-section" id="sources">
          <div class="section-heading">
            <h2 id="sources-heading">Sources</h2>
          </div>
          <div class="source-chip">Text Sources</div>
          <div class="sources-list">
            ${sources.map((source) => `<p class="source-item">${source}</p>`).join('')}
          </div>
        </section>
      </main>
    </div>
  `

  const tocButton = document.querySelector<HTMLButtonElement>('.toc-button')
  const tocPanel = document.querySelector<HTMLElement>('.toc-panel')
  const tocBackdrop = document.querySelector<HTMLButtonElement>('.toc-backdrop')
  const tocLinks = document.querySelectorAll<HTMLButtonElement>('.toc-link')

  const setTocOpen = (isOpen: boolean) => {
    document.body.dataset.tocOpen = String(isOpen)
    tocButton?.setAttribute('aria-expanded', String(isOpen))
    tocPanel?.setAttribute('data-open', String(isOpen))
    tocBackdrop?.setAttribute('data-open', String(isOpen))
  }

  setTocOpen(false)

  tocButton?.addEventListener('click', () => {
    setTocOpen(document.body.dataset.tocOpen !== 'true')
  })

  tocBackdrop?.addEventListener('click', () => setTocOpen(false))

  const scrollToHeading = (targetId: string) => {
    const targetElement = document.getElementById(targetId)
    if (!targetElement) return

    const targetTop = targetElement.getBoundingClientRect().top + window.scrollY
    window.scrollTo({ top: targetTop, behavior: 'smooth' })
  }

  tocLinks.forEach((link) => {
    link.addEventListener('click', () => {
      const targetId = link.dataset.target
      if (!targetId) return

      scrollToHeading(targetId)
      setTocOpen(false)
    })
  })
}
