import './style.css'

const navItems = [
  { label: 'Introduction', targetId: 'introduction-heading' },
  { label: 'Datasets', targetId: 'datasets-heading' },
  { label: 'Methodology', targetId: 'methodology-heading' },
  { label: 'Results', targetId: 'results-heading' },
  { label: 'Conclusion', targetId: 'conclusion-heading' },
  { label: 'Sources', targetId: 'sources-heading' },
]

const teamMembers = ['Raphael Caguat', 'James Wang', 'Lucia Wu']

const datasets = [
  {
    title: 'Photovoltaic Potential',
    summary:
      'Information on the estimated amount of electricity that can be annually generated by photovoltaic systems for any location in Canada. Values are given in kWh/kWp. Data was obtained as a geodatabase file from Natural Resources Canada through the <a href="https://open.canada.ca/data/en/dataset/8b434ac7-aedb-4698-90df-ba77424a551f" target="_blank" rel="noreferrer">Government of Canada Open Government Portal</a>.',
  },
  {
    title: 'Land Cover',
    summary:
      'Placeholder text for the land cover dataset. Replace this with the classification source used to exclude incompatible land uses.',
  },
  {
    title: 'Transmission Lines',
    summary:
      'Placeholder text for proximity to transmission infrastructure. Insert the vector layer or buffered map showing grid access.',
  },
  {
    title: 'Elevation',
    summary:
      'Placeholder text for the elevation layer. Swap in the DEM, slope analysis, or terrain constraint map when ready.',
  },
]

const resultCards = [
  'Placeholder for the final suitability map or ranked district summary.',
  'Placeholder for before-and-after or weighted overlay comparisons.',
  'Placeholder for hectares, percentage, or score distribution statistics.',
]

const sources = [
  'Jamil, U., Bonnington, A., & Pearce, J. M. (2023). The agrivoltaic potential of Canada. Sustainability, 15(4), 3228.',
  'Pena-Calzada, K., Toledo, C., Gargica, J. P., Barrera-Cardoso, E. L., Iriondo-Perez, M. E., Sotolongo-Hernandez, E., & Scognamiglio, A. (2025). Advances and challenges of agrivoltaic in the Americas: a look at its current situation. Agroforestry Systems, 99(1), 8.',
  'Government of Canada. (2022, June 15). Saskatchewan continues to live up to the title of breadbasket of Canada.',
  'Widmer, J., Christ, B., Grenz, J., & Norgrove, L. (2024). Agrivoltaics, a promising new tool for electricity and food production: A systematic review. Renewable and Sustainable Energy Reviews, 192, 114277.',
]

const app = document.querySelector<HTMLDivElement>('#app')

if (app) {
  app.innerHTML = `
    <div class="site-shell">
      <aside class="toc" aria-label="Table of contents">
        <button class="toc-button" type="button" aria-expanded="false" aria-controls="toc-panel">
          <span class="toc-button-lines" aria-hidden="true"><span></span><span></span><span></span></span>
          <span class="sr-only">Toggle table of contents</span>
        </button>

        <div class="toc-panel" id="toc-panel">
          <p class="toc-title">Table Of Contents</p>
          <nav class="toc-links">
            ${navItems
              .map(
                (item) =>
                  `<button type="button" class="toc-link" data-target="${item.targetId}">${item.label}</button>`,
              )
              .join('')}
          </nav>
        </div>

        <button class="toc-backdrop" type="button" aria-hidden="true" tabindex="-1"></button>
      </aside>

      <main class="page" id="top">
        <section class="hero section-card">
          <div class="hero-scene" aria-hidden="true">
            <div class="hero-caption-wrap">
              <h1>Mapping Viable Areas for Agrivolatics in Saskatchewan</h1>
            </div>
          </div>
        </section>

        <section class="section-card team-section">
          <div class="section-heading">
            <h2>The Team</h2>
          </div>
          <div class="team-grid">
            ${teamMembers.map((member) => `<article class="team-card">${member}</article>`).join('')}
          </div>
        </section>

        <section class="section-card" id="introduction">
          <div class="section-heading">
            <h2 id="introduction-heading">Introduction</h2>
          </div>

          <div class="intro-flow">
            <figure class="content-figure intro-figure">
              <div class="figure-placeholder figure-map">
                <span>saskatchewan crop map</span>
              </div>
            </figure>

            <div class="prose intro-prose">
              <p>
                Globally, countries must deal with the combined effects of population growth and climate change, which make it difficult to expand renewable energy sources while meeting increasing food demand. As the world works to limit global warming to +1.5°C above industrial levels as described in the Paris Agreement (UNFCCC, 2016), addressing this challenge only becomes more pressing. Solar photovoltaic (PV) energy is a key part to addressing this problem; however, it comes with the caveat of requiring significant land area. This need for land leads to conflicts with the agricultural sector (Widmer et al., 2024). As a result, agrivoltaics, which is essentially the co-development of land for both PV and agriculture, has emerged as a solution to this issue (Jamil et al., 2023; Pena-Calzada et al., 2024; Widmer et al., 2024).
              </p>
              <p>
                Saskatchewan, which is known as the breadbasket of Canada, accounted for 39.2% of Canada’s total farm area as of 2021 — that is the largest share among all Canadian provinces (Government of Canada, 2022). Additionally, about two-thirds of this total farm area, which equates to approximately 40 million acres, consists of cropland. Thus, it is theorized that even using a tiny portion of this land for agrivoltaics would allow the province to offset fuel-based electricity generation and would contribute greatly to the country’s energy needs.
                </p>
              <p>
                Overall, the goal of this study is to identify which areas in Saskatchewan offer the strongest suitability for agrivoltaics deployment through a Multi-Criteria Evaluation.
            </p>
            </div>
          </div>
        </section>

        <section class="section-card" id="datasets">
          <div class="section-heading">
            <h2 id="datasets-heading">Datasets</h2>
          </div>

          <div class="prose dataset-intro">
            <p>
              The majority of our data was obtained for free from the Government of Canada Open Government Portal.
              The sole exception to this is the transmission line data, which was obtained from ArcGIS Online.
            </p>
            <p>
              We obtained the most up-to-date versions of our data possible. However, it should be noted that this
              can mean different datasets are from different years (i.e. land cover data was last updated in 2020,
              crop type data was last updated in 2024).
            </p>
          </div>

          <div class="dataset-list">
            ${datasets
              .map(
                (dataset) => `
                  <article class="dataset-row">
                    <div class="dataset-copy">
                      <h3>${dataset.title}</h3>
                      <div class="figure-placeholder dataset-image">
                        <span>some ${dataset.title.toLowerCase()} image</span>
                      </div>
                    </div>
                    <div class="dataset-text">
                      <p class="dataset-label">${dataset.title} Explanation</p>
                      <p class="dataset-summary">${dataset.summary}</p>
                      <p class="dataset-filler">blah blah b ${dataset.title.toLowerCase()} brrr f fds fsd fa w r f dsf sd f jifdojoij</p>
                    </div>
                  </article>
                `,
              )
              .join('')}
          </div>
        </section>

        <section class="section-card" id="methodology">
          <div class="section-heading">
            <h2 id="methodology-heading">Methodology</h2>
          </div>
          <div class="methodology-box">IDK WHAT THIS IS GONNA LOOK LIKE YET</div>
        </section>

        <section class="section-card" id="results">
          <div class="section-heading">
            <h2 id="results-heading">Results</h2>
          </div>
          <div class="results-box">so epic good yes</div>
          ${resultCards.map((text) => `<div class="results-text">${text}</div>`).join('')}
          <div class="results-text results-filler">blah blah b landcover brrr</div>
          <div class="results-text results-filler">blah blah b transmission brrr</div>
          <div class="results-text results-filler">blah blah b elevation stuff rahhh brrr</div>
        </section>

        <section class="section-card conclusion-section" id="conclusion">
          <div class="section-heading">
            <h2 id="conclusion-heading">Conclusion</h2>
          </div>
          <div class="conclusion-box">in conclusion this is win</div>
        </section>

        <section class="section-card sources-section" id="sources">
          <div class="section-heading">
            <h2 id="sources-heading">Sources</h2>
          </div>
          <div class="source-chip">Text Sources</div>
          <div class="sources-list">
            ${sources.map((source) => `<p>${source}</p>`).join('')}
          </div>
        </section>
      </main>
    </div>
  `

  const tocButton = document.querySelector<HTMLButtonElement>('.toc-button')
  const tocPanel = document.querySelector<HTMLElement>('.toc-panel')
  const tocBackdrop = document.querySelector<HTMLButtonElement>('.toc-backdrop')
  const tocLinks = document.querySelectorAll<HTMLButtonElement>('.toc-link')

  const setTocOpen = (isOpen: boolean) => {
    document.body.dataset.tocOpen = String(isOpen)
    tocButton?.setAttribute('aria-expanded', String(isOpen))
    tocPanel?.setAttribute('data-open', String(isOpen))
    tocBackdrop?.setAttribute('data-open', String(isOpen))
  }

  setTocOpen(false)

  tocButton?.addEventListener('click', () => {
    setTocOpen(document.body.dataset.tocOpen !== 'true')
  })

  tocBackdrop?.addEventListener('click', () => setTocOpen(false))

  const scrollToHeading = (targetId: string) => {
    const targetElement = document.getElementById(targetId)
    if (!targetElement) return

    const targetTop = targetElement.getBoundingClientRect().top + window.scrollY
    window.scrollTo({ top: targetTop, behavior: 'smooth' })
  }

  tocLinks.forEach((link) => {
    link.addEventListener('click', () => {
      const targetId = link.dataset.target
      if (!targetId) return

      scrollToHeading(targetId)
      setTocOpen(false)
    })
  })
}
